로직 상 문제가 없다고 판단했는데 제출할 때마다 런타임 에러가 발생했고 원인은 RecursionError였음.
옆에 있던 민혁이형의 조언을 받아서 해결할 수 있었는데 python3의 최대 재귀 깊이와 관련된 문제였음
기본적으로 설정되어 있는 python3의 최대 재귀 깊이는 1000인데 이번 10026번 문제의 경우 더 깊은 재귀가 필요했음
따라서 sys 라이브러리의 setrecursionlimit 메소드를 사용해서 최대 재귀 깊이를 2500으로 변경해서 해결할 수 있었음

